/**
 * Realistic 1CS API response mocks.
 *
 * These match the shapes returned by the @defuse-protocol/one-click-sdk-typescript
 * SDK methods: getQuote(), submitDepositTx(), getExecutionStatus().
 *
 * The swap-as-resource service uses `swapType: EXACT_INPUT` — the buyer
 * signs for an exact `amountIn`, the destination amount becomes the
 * variable. Slippage upside lands on the buyer.
 */

import type { QuoteResponseRecord, SwapRequestInput } from "../types.js";
import type { StatusPollResult, DepositNotifyResult } from "../payment/settler.js";
import { ORIGIN_ASSET_IN, DESTINATION_PRESETS } from "./mock-config.js";
import { FACILITATOR_ADDRESS } from "./mock-wallets.js";

// ═══════════════════════════════════════════════════════════════════════
// Deposit address (the key binding between x402 payTo and 1CS)
// ═══════════════════════════════════════════════════════════════════════

/**
 * A realistic 1CS deposit address.
 * In production, this is generated by 1CS for each quote.
 */
export const MOCK_DEPOSIT_ADDRESS = "0x7a16fF8270133F063aAb6C9977183D9e72835428";

// ═══════════════════════════════════════════════════════════════════════
// Buyer swap inputs
// ═══════════════════════════════════════════════════════════════════════

/**
 * Build a realistic {@link SwapRequestInput} the buyer would supply via
 * query string. Defaults to the NEAR preset; pass overrides (often from
 * {@link DESTINATION_PRESETS}) to test other destination chains.
 */
export function mockSwapInputs(
  overrides: Partial<SwapRequestInput> = {},
): SwapRequestInput {
  return {
    ...DESTINATION_PRESETS.near,
    amountIn: "10000000", // 10 USDC (6 decimals)
    ...overrides,
  };
}

// ═══════════════════════════════════════════════════════════════════════
// Quote response
// ═══════════════════════════════════════════════════════════════════════

/**
 * Build a realistic 1CS QuoteResponse (as stored in SwapState.quoteResponse).
 *
 * Represents an EXACT_INPUT quote: buyer signs for an exact 10 USDC on
 * Base, destination amount lands at ~9.985 USDC on the chosen chain
 * (after 1CS fee + slippage). This matches the swap-as-resource semantics.
 *
 * @param inputs   Buyer's swap parameters. Defaults to {@link mockSwapInputs}.
 * @param overrides Top-level QuoteResponseRecord overrides.
 */
export function mockQuoteResponse(
  inputs: SwapRequestInput = mockSwapInputs(),
  overrides: Partial<QuoteResponseRecord> = {},
): QuoteResponseRecord {
  const deadline = new Date(Date.now() + 10 * 60 * 1000); // 10 min from now

  return {
    correlationId: "corr-a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    timestamp: new Date().toISOString(),
    signature: "mock-1cs-quote-signature-base64",
    quoteRequest: {
      dry: false,
      swapType: "EXACT_INPUT",
      slippageTolerance: 50,
      originAsset: ORIGIN_ASSET_IN,
      depositType: "ORIGIN_CHAIN",
      destinationAsset: inputs.destinationAsset,
      amount: inputs.amountIn,
      refundTo: inputs.refundAddress ?? FACILITATOR_ADDRESS,
      refundType: "ORIGIN_CHAIN",
      recipient: inputs.destinationAddress,
      recipientType: "DESTINATION_CHAIN",
      deadline: deadline.toISOString(),
    },
    quote: {
      depositAddress: MOCK_DEPOSIT_ADDRESS,
      // EXACT_INPUT: amountIn echoes inputs.amountIn (the buyer's exact authorisation).
      amountIn: inputs.amountIn,
      amountInFormatted: (Number(inputs.amountIn) / 1e6).toFixed(2),
      amountInUsd: (Number(inputs.amountIn) / 1e6).toFixed(2),
      minAmountIn: inputs.amountIn,
      // Destination amount is variable under EXACT_INPUT — ~9.985 USDC after fees.
      amountOut: "9985000",
      amountOutFormatted: "9.985",
      amountOutUsd: "9.99",
      minAmountOut: "9950000", // 9.95 USDC — slippage floor
      deadline: deadline.toISOString(),
      timeWhenInactive: new Date(deadline.getTime() + 5 * 60 * 1000).toISOString(),
      timeEstimate: 30, // ~30 seconds estimated settlement
    },
    ...overrides,
  };
}

// ═══════════════════════════════════════════════════════════════════════
// Deposit notification response
// ═══════════════════════════════════════════════════════════════════════

/**
 * Response from POST /v0/deposit/submit after notifying 1CS of the tx hash.
 */
export function mockDepositNotifyResponse(
  overrides: Partial<DepositNotifyResult> = {},
): DepositNotifyResult {
  return {
    status: "KNOWN_DEPOSIT_TX",
    correlationId: "corr-a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    ...overrides,
  };
}

// ═══════════════════════════════════════════════════════════════════════
// Status polling responses
// ═══════════════════════════════════════════════════════════════════════

/**
 * A typical happy-path status polling sequence with rich `swapDetails`.
 *
 * The terminal `SUCCESS` includes the new fields the receipt builder
 * surfaces in `extensions.crossChain`: `slippage`, `amountOutFormatted`,
 * `amountOutUsd`. Without these, receipt assertions degrade gracefully
 * (the helper omits the field), which is the correct behavior under
 * mid-flight observation races.
 *
 * @param options.destinationTxHash       Override the destination tx hash.
 * @param options.destinationExplorerUrl  Override the explorer URL.
 */
export function mockHappyPathStatusSequence(options: {
  destinationTxHash?: string;
  destinationExplorerUrl?: string;
} = {}): StatusPollResult[] {
  const destHash = options.destinationTxHash ?? "9XzKqRuAfcE7vWsH3bJpNmD4yT8gFwCeL2xYnG5oU6k";
  const destExplorerUrl = options.destinationExplorerUrl ?? `https://nearblocks.io/txns/${destHash}`;

  return [
    { status: "KNOWN_DEPOSIT_TX" },
    { status: "PROCESSING" },
    {
      status: "SUCCESS",
      swapDetails: {
        originChainTxHashes: [
          {
            hash: "0xf1e2d3c4b5a697f8e9d0c1b2a3948576061728394a5b6c7d8e9f0a1b2c3d4e5f",
            explorerUrl: "https://basescan.org/tx/0xf1e2d3c4b5a697f8e9d0c1b2a3948576061728394a5b6c7d8e9f0a1b2c3d4e5f",
          },
        ],
        destinationChainTxHashes: [
          {
            hash: destHash,
            explorerUrl: destExplorerUrl,
          },
        ],
        amountIn: "10000000",
        amountOut: "9985000",
        amountOutFormatted: "9.985",
        amountOutUsd: "9.99",
        slippage: 0.0015,
      },
    },
  ];
}

/**
 * A failed swap sequence (e.g., liquidity dried up during settlement).
 */
export function mockFailedStatusSequence(): StatusPollResult[] {
  return [
    { status: "KNOWN_DEPOSIT_TX" },
    { status: "PROCESSING" },
    {
      status: "FAILED",
      swapDetails: {
        originChainTxHashes: [
          {
            hash: "0xf1e2d3c4b5a697f8e9d0c1b2a3948576061728394a5b6c7d8e9f0a1b2c3d4e5f",
            explorerUrl: "https://basescan.org/tx/0xf1e2d3c4b5a697f8e9d0c1b2a3948576061728394a5b6c7d8e9f0a1b2c3d4e5f",
          },
        ],
        refundedAmount: "10000000",
      },
    },
  ];
}

/**
 * A refunded swap sequence (1CS returned funds to refundTo).
 */
export function mockRefundedStatusSequence(): StatusPollResult[] {
  return [
    { status: "PENDING_DEPOSIT" },
    { status: "INCOMPLETE_DEPOSIT" },
    {
      status: "REFUNDED",
      swapDetails: {
        originChainTxHashes: [],
        refundedAmount: "10000000",
      },
    },
  ];
}
