/**
 * x402-spec-compliant payment payloads with real EIP-712 signatures.
 *
 * These factory functions generate PaymentPayloadRecord objects that
 * exercise the full cryptographic verification path in verifier.ts.
 * The signatures are real — generated by ethers.Wallet.signTypedData —
 * so they test actual ecrecover logic, not just mock stubs.
 *
 * @see x402 spec — PaymentPayload shape
 * @see EIP-3009 — TransferWithAuthorization
 * @see Permit2 — PermitWitnessTransferFrom
 */

import { ethers } from "ethers";
import {
  authorizationTypes,
  permit2WitnessTypes,
  PERMIT2_ADDRESS,
  x402ExactPermit2ProxyAddress,
} from "@x402/evm";
import type { PaymentPayloadRecord, PaymentRequirementsRecord } from "../types.js";
import { MOCK_DEPOSIT_ADDRESS } from "./mock-1cs-responses.js";
import { buyerWallet } from "./mock-wallets.js";
import {
  CHAIN_ID,
  NETWORK,
  USDC_ADDRESS,
  TOKEN_NAME,
  TOKEN_VERSION,
} from "./mock-config.js";

// ═══════════════════════════════════════════════════════════════════════
// PaymentRequirements (the x402 402 response that the buyer accepts)
// ═══════════════════════════════════════════════════════════════════════

/**
 * Build realistic PaymentRequirements matching what the gateway returns
 * in the HTTP 402 response.
 */
export function mockPaymentRequirements(
  overrides: Partial<PaymentRequirementsRecord> = {},
): PaymentRequirementsRecord {
  return {
    scheme: "exact",
    network: NETWORK,
    asset: USDC_ADDRESS,
    amount: "10500000",           // 10.50 USDC
    payTo: MOCK_DEPOSIT_ADDRESS,  // 1CS deposit address
    maxTimeoutSeconds: 300,       // 5 minutes
    extra: {
      name: TOKEN_NAME,
      version: TOKEN_VERSION,
      assetTransferMethod: "eip3009",
    },
    ...overrides,
  };
}

// ═══════════════════════════════════════════════════════════════════════
// EIP-3009 payload (TransferWithAuthorization)
// ═══════════════════════════════════════════════════════════════════════

/**
 * Generate a full x402 PaymentPayload with a real EIP-3009 signature.
 *
 * The buyer signs a TransferWithAuthorization that directs funds to the
 * 1CS deposit address. The signature is cryptographically valid and will
 * pass ethers.verifyTypedData().
 *
 * @param wallet   — Signer wallet (defaults to the mock buyer).
 * @param options  — Override any authorization fields.
 */
export async function signEIP3009Payload(
  wallet: ethers.Wallet = buyerWallet,
  options: {
    to?: string;
    value?: string;
    validAfter?: string;
    validBefore?: string;
    nonce?: string;
    requirements?: Partial<PaymentRequirementsRecord>;
  } = {},
): Promise<{
  payload: PaymentPayloadRecord;
  requirements: PaymentRequirementsRecord;
}> {
  const requirements = mockPaymentRequirements(options.requirements);
  const nowSec = Math.floor(Date.now() / 1000);

  const authorization = {
    from: wallet.address,
    to: options.to ?? requirements.payTo,
    value: options.value ?? requirements.amount,
    validAfter: options.validAfter ?? "0",
    validBefore: options.validBefore ?? String(nowSec + 300),
    nonce: options.nonce ?? ("0x" + ethers.hexlify(ethers.randomBytes(32)).slice(2)),
  };

  // EIP-712 domain for the token contract
  const domain: ethers.TypedDataDomain = {
    name: TOKEN_NAME,
    version: TOKEN_VERSION,
    chainId: CHAIN_ID,
    verifyingContract: USDC_ADDRESS,
  };

  // EIP-712 types (from @x402/evm)
  const types = {
    TransferWithAuthorization: authorizationTypes.TransferWithAuthorization.map(
      (f) => ({ name: f.name, type: f.type }),
    ),
  };

  // The message to sign
  const message = {
    from: authorization.from,
    to: authorization.to,
    value: authorization.value,
    validAfter: authorization.validAfter,
    validBefore: authorization.validBefore,
    nonce: authorization.nonce,
  };

  // Sign with the buyer's wallet
  const signature = await wallet.signTypedData(domain, types, message);

  const payload: PaymentPayloadRecord = {
    x402Version: 1,
    accepted: requirements,
    payload: {
      signature,
      authorization,
    },
  };

  return { payload, requirements };
}

// ═══════════════════════════════════════════════════════════════════════
// Permit2 payload (PermitWitnessTransferFrom)
// ═══════════════════════════════════════════════════════════════════════

/**
 * Generate a full x402 PaymentPayload with a real Permit2 signature.
 *
 * The buyer signs a PermitWitnessTransferFrom via the Permit2 contract,
 * with the x402ExactPermit2Proxy as the spender. The witness.to field
 * points to the 1CS deposit address.
 *
 * @param wallet   — Signer wallet (defaults to the mock buyer).
 * @param options  — Override any permit2 authorization fields.
 */
export async function signPermit2Payload(
  wallet: ethers.Wallet = buyerWallet,
  options: {
    to?: string;
    amount?: string;
    deadline?: string;
    validAfter?: string;
    nonce?: string;
    requirements?: Partial<PaymentRequirementsRecord>;
  } = {},
): Promise<{
  payload: PaymentPayloadRecord;
  requirements: PaymentRequirementsRecord;
}> {
  const requirements = mockPaymentRequirements({
    extra: {
      name: TOKEN_NAME,
      version: TOKEN_VERSION,
      assetTransferMethod: "permit2",
    },
    ...options.requirements,
  });
  const nowSec = Math.floor(Date.now() / 1000);

  const permit2Authorization = {
    from: wallet.address,
    permitted: {
      token: USDC_ADDRESS,
      amount: options.amount ?? requirements.amount,
    },
    spender: x402ExactPermit2ProxyAddress,
    nonce: options.nonce ?? String(Math.floor(Math.random() * 1_000_000)),
    deadline: options.deadline ?? String(nowSec + 300),
    witness: {
      to: options.to ?? requirements.payTo,
      validAfter: options.validAfter ?? "0",
    },
  };

  // Permit2 uses a fixed EIP-712 domain
  const domain: ethers.TypedDataDomain = {
    name: "Permit2",
    verifyingContract: PERMIT2_ADDRESS,
    chainId: CHAIN_ID,
  };

  // EIP-712 types (from @x402/evm)
  const types: Record<string, Array<{ name: string; type: string }>> = {};
  for (const [key, fields] of Object.entries(permit2WitnessTypes)) {
    types[key] = fields.map((f: { name: string; type: string }) => ({
      name: f.name,
      type: f.type,
    }));
  }

  // The message to sign
  const message = {
    permitted: {
      token: permit2Authorization.permitted.token,
      amount: permit2Authorization.permitted.amount,
    },
    spender: permit2Authorization.spender,
    nonce: permit2Authorization.nonce,
    deadline: permit2Authorization.deadline,
    witness: {
      to: permit2Authorization.witness.to,
      validAfter: permit2Authorization.witness.validAfter,
    },
  };

  // Sign with the buyer's wallet
  const signature = await wallet.signTypedData(domain, types, message);

  const payload: PaymentPayloadRecord = {
    x402Version: 1,
    accepted: requirements,
    payload: {
      signature,
      permit2Authorization,
    },
  };

  return { payload, requirements };
}
